apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-db
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.37.105
